# Generated by Django 3.1.4 on 2022-04-17 05:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number_plate', models.CharField(blank=True, max_length=150, null=True)),
                ('car_model', models.CharField(blank=True, max_length=150, null=True)),
                ('car_color', models.CharField(blank=True, max_length=150, null=True)),
                ('car_location', models.CharField(blank=True, max_length=150, null=True)),
                ('car_image', models.ImageField(blank=True, null=True, upload_to='car/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PCNCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pcnCode', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PCNTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_of_creation', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=150, null=True)),
                ('carDetails', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pcnCars', to='carDetails.cardetails')),
                ('pcnCode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pcnCodes', to='carDetails.pcncode')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pcnUsers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
