# Generated by Django 3.1.4 on 2022-04-17 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carDetails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcncode',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
