# Generated by Django 3.1.4 on 2022-05-31 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carDetails', '0002_pcncode_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='evidence/')),
                ('carDetail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carDetails', to='carDetails.cardetails')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
